export const students = [
  {
    id: 1,
    name: "Hayotbek Yo'ldashev",
    status: 'IT',
    adress: 'Qashqadarya',
    age: '22',
  },
  {
    id: 2,
    name: 'Shokhrukh Toshpulatov',
    status: 'Ekonomist',
    adress: 'Qashqadarya',
    age: '22',
  },
  {
    id: 4,
    name: 'Barno Rakhmatova',
    status: 'Teacher',
    adress: 'Qashqadarya',
    age: '30',
  },
  {
    id: 5,
    name: 'Temur Raimov',
    status: 'IT',
    adress: 'Qashqadarya',
    age: '22',
  },
  {
    id: 6,
    name: 'Jamshid Ibragimov',
    status: 'Busnessman',
    adress: 'Qashqadarya',
    age: '22',
  },
  {
    id: 7,
    name: 'Yunus Nurimov',
    status: 'Mechenic',
    adress: 'Qashqadarya',
    age: '22',
  },
  {
    id: 8,
    name: "Yo'ldasheva Umida",
    status: 'Designer',
    adress: 'Qashqadarya',
    age: '25',
  },
  {
    id: 9,
    name: 'Abdusalomov Abdusalom',
    status: 'Baby',
    adress: 'Qashqadarya',
    age: '1',
  },
  {
    id: 10,
    name: 'Murodova Arjumand',
    status: 'Pupil',
    adress: 'Qashqadarya',
    age: '15',
  },
  {
    id: 11,
    name: 'Safarov Jahongir ',
    status: 'Seller',
    adress: 'Qashqadarya',
    age: '27',
  },
  {
    id: 12,
    name: 'Yoldashev Jahongir',
    status: 'Military',
    adress: 'Qashqadarya',
    age: '30',
  },
  {
    id: 13,
    name: 'Yunusov Jahongir',
    status: 'Logistic',
    adress: 'Qashqadarya',
    age: '30',
  },
  {
    id: 14,
    name: 'Yunusov Orzubek',
    status: 'Medic',
    adress: 'Qashqadarya',
    age: '22',
  },
  {
    id: 15,
    name: 'Yunusov Javlon',
    status: 'Busunessman',
    adress: 'Qashqadarya',
    age: '28',
  },
];
